### ISSUE TITLE
No timestamps on docx and vtt

### ISSUE THREAD

**Issue by pagkly** [kibaffo33/aws_transcribe_to_docx#11]
Python 3.7.6

I have used tscribe a few times before and it would show the timing
![image](https://user-images.githubusercontent.com/28628331/80554467-9e68ce80-8a10-11ea-89f7-702a716101d0.png)

but now it doesn't:

![image](https://user-images.githubusercontent.com/28628331/80554503-bd676080-8a10-11ea-8d31-6fbd7fe0a871.png)

Is there a new setting for that or there is some settings in the AWS I need to have?
On a side note, I converted the same newer .json transcript to .srt using `aws-transcribe-to-srt`
and it works just fine showing the times

![image](https://user-images.githubusercontent.com/28628331/80554665-38c91200-8a11-11ea-8905-2440d8db56c3.png)

**Comment by kibaffo33** [comment]
Did your transcript job have speaker identification or channel identification enabled?

**Comment by kibaffo33** [comment]
Can you post your source material?
(json file)

**Comment by pagkly** [comment]
[asrOutput.zip](https://github.com/kibaffo33/aws_transcribe_to_docx/files/4549977/asrOutput.zip)

**Comment by kibaffo33** [comment]
Hi @pagkly, thanks for sharing.

The source material appears different to the screenshots you posted. I've searched for a few phrases from the screenshots but cant identify them in the job you sent.

I've ran your `asrOutput.json` through `tscribe 1.3.1` on `python 3.8.2`. It seemed to come out as expected for me. I see you mentioned python 3.7.6 earlier. What version of tscribe are you running? Could you check it is the latest, if not update and run again then let me know?

Thanks

![Screenshot 2020-04-29 at 20 18 35](https://user-images.githubusercontent.com/22222686/80637489-fde9cd00-8a56-11ea-8fa2-ec671d0b55eb.png)

**Comment by kibaffo33** [comment]
No response received for five days, this issue will be closed tomorrow.

**Comment by kibaffo33** [comment]
Issue does not appear to be as first reported. Unable to replicate with test data provided. No response from reporting person.

**Comment by pagkly** [comment]
@kibaffo33 just want to update that it's due to the channel/speaker identification.
I accidentally sent you the working one and compare it to the one that I have problems with.
I did not specify the setting in my boto3 python script.
Thank you
