### ISSUE TITLE
option to merge adjacent rows in a conversation

### ISSUE THREAD

**Issue by timfam** [kibaffo33/aws_transcribe_to_docx#12]
Hi thanks for the script, an option to reduce duplicate speaker rows will be great. My first time using AWS transcribe and your script is coming in very handy. 
![merge-speaker](https://user-images.githubusercontent.com/10576880/80768839-816bf280-8b19-11ea-8699-f05a7d001a08.png)

Thanks

**Comment by kibaffo33** [comment]
Hi @timfam 

I’ve given some consideration to your request and can see how merging rows could be useful. 

My thoughts have always been that I do not wish for this package to modify the source material, in this case by merging rows. I think of this package as similar to turning a JPEG into a PNG. The picture should still be the same.

There are many inaccuracies in the transcribe output. Depending on your use case you may find this entirely acceptable, entirely unacceptable, or somewhere in between. I think beginning to fix inaccuracies by doing things like merging rows, splitting rows (a similar request this week), renaming speakers, tidying punctuation, the list goes on, could lead this package down a long long rabbit hole that I don’t wish to go down. Changes like these should happen by improvement at source. You could make your suggestion to AWS if you haven’t already. 

Feel free to fork this repo and modify the code to your suiting. I hope this explanation makes sense and isn’t too negative!

Thanks for getting in touch

**Comment by timfam** [comment]
Thanks for the reply, I see your point this should be fixed at source.
