### ISSUE TITLE
various issues when using redacted json files due to the "confidence" attribute

### ISSUE THREAD

**Issue by cmanasseh** [kibaffo33/aws_transcribe_to_docx#13]
tscribe.write ("redacted-output.json", format="csv")
you get a 
KeyError: 'confidence'
error. 
attached __init__.py has the fixes
[__init__ .txt](https://github.com/kibaffo33/aws_transcribe_to_docx/files/4636135/__init__.txt)

**Comment by kibaffo33** [comment]
Thanks for raising this issue. I'll take a look into it.

**Comment by kibaffo33** [comment]
To make this issue more workable, could you please...

- Add a test to demonstrate the issue/shortcoming
- Submit the changes as a PR, rather than a txt file 

Thank you

**Comment by kibaffo33** [comment]
No response for 6 months, closing issue
