### ISSUE TITLE
Anaconda Issues

### ISSUE THREAD

**Issue by physiodetective** [kibaffo33/aws_transcribe_to_docx#14]
hi - this works great via the command line on my rMBP15 running OSX 10.15.5

I have installed Homebrew and Anaconda and ensured they are up to date. 

I have also installed Python 3 and ensured it is the latest edition.

When I try to import tscribe in a jupyter notebook, it comes back with the error below...

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-d0fe49cc6f2c> in <module>
----> 1 import tscribe

ModuleNotFoundError: No module named 'tscribe'

Any help would be appreciated!

Great piece of code by the way, especially for a noob like me :) (I am a physical therapist using this to get transcriptions of my consults). 

Thanks!

**Comment by kibaffo33** [comment]
Hi there.

Thanks for the positive feedback. 

From the error trace back you posted, this sounds like an environment-related issue rather than the package code. 

Is your notebook in a virtual environment?

Could you describe how you start your notebook up, and do you have any other packages imported? Might be easier if you could share your code. 

Thanks

**Comment by physiodetective** [comment]
Hi bob - i think you are right re the environment issue. I am doing this on
my macbook pro, even though I have parallels so I can run windows, I am
doing it via the terminal.app on my laptop.

1. I open anaconda-navigator
2. I then launch "jupyter notebook"
3. I navigate to the location where I have my notebook
4. I carefully type "import tscribe" and run it - gives me the error
message.

If you have any hints, please let me know. I would prefer to use it so I
can more easily copy and paste the filename path. But doing it line by line
is fine. Thanks

*Antony Lo*
*APA Musculoskeletal Physiotherapist*
Master in Manual Therapy (UWA)
B.App.Sc.(Physio)(USyd)

*Sydney Sports Therapy*
Level 1 - Above the Bottle-O
4/83 Mulga Road
Oatley NSW 2223
Mon - Thu
*Bookings on 9586 4696*

*0410 440 506*


*www.physiodetective.com <http://www.physiodetective.com/>*
*www.mypteducation.com  <http://www.mypteducation.com/>*
*www.myphysios.com.au <http://www.myphysios.com.au/>*

**Comment by kibaffo33** [comment]
Thanks for the update.

Sounds to me like you need to install the package to be able to import it.

I'm not familiar with anaconda myself, but at first glance of the google results I'd suggest going to the Environment tab an installing `tscribe` from there. Alternatively, you could open your environment Terminal and try `conda install tscribe`. This might be a helpful resource: https://docs.anaconda.com/anaconda/navigator/tutorials/manage-packages/#installing-a-package.

The way I'm familiar with would be to start a virtual environment, install the package and write a script or start a jupyter notebook from there. This requires `virtualenv` -> `python3 -m pip install virtualenv`

```bash
python3 -m virtualenv venv
source venv/bin/activate
python -m pip install tscribe
```
Having done either, you can begin to use the package...

```python
import tscribe
tscribe.write("asrOutput.json")
tscribe.write("asrOutput.json", save_as="Transcript.docx")
```

**Comment by physiodetective** [comment]
Thanks - very helpful - i will try that.

Cheers

*Antony Lo*
*APA Musculoskeletal Physiotherapist*
Master in Manual Therapy (UWA)
B.App.Sc.(Physio)(USyd)

*0410 440 506*


*www.physiodetective.com <http://www.physiodetective.com/>*
*www.mypteducation.com  <http://www.mypteducation.com/>*
*www.myphysios.com.au <http://www.myphysios.com.au/>*

*The Physio Detective*
Parkside Drive
Kogarah Bay, NSW, 2217
Mon - Fri
*Bookings on 0410 440 506 or physiodetective.com/bookings
<http://physiodetective.com/bookings>*

*The Physio Detective @ **Sydney **Sports Therapy*
Level 1 - Above the Bottle-O
4/83 Mulga Road
Oatley NSW 2223
Mon, Wed, Thu
*Bookings on 9586 4696 or physiodetective.com/bookings
<http://physiodetective.com/bookings>*
