### ISSUE TITLE
missing docx from requirments

### ISSUE THREAD

**Issue by ChrisUAM** [kibaffo33/aws_transcribe_to_docx#2]
When trying to look at this project I got an error:
"error: can't copy 'docx/templates/default-docx-template': doesn't exist or not a regular file"
Googleing the error found a different project with same, so I tried manually installing docx
"pip install python-docx==0.8.10"
Re-ran install successfully.

**Comment by kibaffo33** [comment]
Thanks for raising an issue.
This is an anomoly with `python-docx`; the package is named `python-docx` but imported as `docx`.
`python-docx==0.8.6` is already in `requirements.txt`
