### ISSUE TITLE
UTF-8 characters not correctly displayed in final Word document

### ISSUE THREAD

**Issue by jfix** [kibaffo33/aws_transcribe_to_docx#4]
I've tested the output of an English audio file and it worked flawlessly! Wow, this is really great!

I then had a French audio file transcribed by AWS Transcribe, and having run your script, the resulting DOCX file doesn't seem to handle the accents and other characters very well. For example, I get the following output 

```
directeur gÃ©nÃ©ral
```

when one would expect

```
directeur général
```

I checked the encoding of the JSON file produced by AWS Transcribe and it is UTF-8.
Not being a Python developer, just a happy user, I can only submit what appears to be a bug (or a missing option on my end?) rather than submit a PR. :-(

Thanks again!

**Comment by kibaffo33** [comment]
I've updated the part which loads the json file to recognise utf-8 encoding (https://github.com/kibaffo33/aws_transcribe_to_docx/commit/84b65dbdc3e790bffeddc04c6e1a356d052160fa). I hope this fixes the issue. Let me know...

Also, this is now a package which you can `pip install ...` - hopefully this makes it easier for you too. README updated with usage...

**Comment by jfix** [comment]
Cool, thanks! I'll check it out. 👍
