### ISSUE TITLE
Error when trying to execute

### ISSUE THREAD

**Issue by nigetwo7four** [kibaffo33/aws_transcribe_to_docx#6]
Hi when I try to use the code I get the following issue

import tscribe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\nijel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tscribe\__init__.py", line 3, in <module>

**Comment by nigetwo7four** [comment]
Tried running outside of python and get the following

C:\Users\nijel\Documents\Podcasts>dir ron*
 Volume in drive C is OS
 Volume Serial Number is AAA1-216A

 Directory of C:\Users\nijel\Documents\Podcasts

12/07/2019  11:05            37,888 Ron Rosenhead interview 190711.aup
12/07/2019  11:08       153,308,160 Ron Rosenhead interview 190711.mp3
12/07/2019  11:05    <DIR>          Ron Rosenhead interview 190711_data
11/07/2019  20:18        61,009,011 Ron Rosenhead.mp4
12/07/2019  12:40    <DIR>          ron transcibe
12/07/2019  12:37             6,329 ron transcibe.zip
12/07/2019  12:37         2,347,953 ront.json
               5 File(s)    216,709,341 bytes
               2 Dir(s)  647,467,098,112 bytes free

C:\Users\nijel\Documents\Podcasts>python tscribe.write("C:\Users\nijel\Documents\Podcasts\ront.json" save_as="nige")
python: can't open file 'tscribe.write(C:\Users\nijel\Documents\Podcasts\ront.json': [Errno 22] Invalid argument

C:\Users\nijel\Documents\Podcasts>

**Comment by kibaffo33** [comment]
Could you run the command `pip show tscribe` on your command line and past the results? Thanks

**Comment by kibaffo33** [comment]
Looks like you are passing the python code to where your os is expecting a filename of a python script. I recommend the following usage (providing you have tscribe pip installed)...

From your directory C:\Users\nijel\Documents\Podcasts...
```bash
python
```
```python
import tscribe
tscribe.write('ront.json')
exit()
```
Let me know how it goes...
